[project]
name = "games-project-volkov"
version = "0.1.0"
description = "Игра"
dependencies = [
    "prompt>=0.4.1",
]
requires-python = ">=3.10"

[project.scripts]
VD-games = "games_project_volkov.VD_games.scripts.VD_main:main"
VD-even = "games_project_volkov.VD_games.scripts.VD_even:play_even_game"

[tool.hatch.build.targets.wheel]
packages = ["src/games_project_volkov"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.15.1",
]
